version: '3'
services:
  db:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: maintenance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - .docker/postgresql/data:/var/lib/postgresql/data
 